### ISSUE TITLE
sbt 1.2 support

### ISSUE THREAD

**Issue by SethTisue** [lightbend/dbuild#212]
I tried using sbt 1.2.0-RC1 in the community build and got a lot of errors like:

```
[akka-http-json] [error] java.lang.NoSuchMethodError: sbt.internal.Load$.reapply(Lscala/collection/Seq;Lsbt/internal/BuildStructure;Lsbt/util/Show;)Lsbt/internal/BuildStructure;
```

the full log is here: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3137/consoleFull

**Comment by dwijnand** [comment]
The new signature includes a logger: https://github.com/sbt/sbt/pull/4231/files#diff-2d60fc47edf4d9f1c9de681e52e5cd47R362

**Comment by eed3si9n** [comment]
It might be worth tackling this ourselves since Toni's out for a while this summer.

**Comment by SethTisue** [comment]
yeah, I've been wondering whether to speak up here and say "are you really sure you want to release 1.2 without community build verification"?

**Comment by eed3si9n** [comment]
Here's the PR - https://github.com/lightbend/dbuild/pull/213

**Comment by SethTisue** [comment]
for the community build, I'm interested in having a dbuild build that includes this fix, since projects are starting to adopt sbt 1.2, which means I have to freeze or fork them. already had to do it for one project, more are sure to come in the coming days & weeks

**Comment by cunei** [comment]
I'm working on it, but the PR is not much help. All plugins for sbt 1.0.x, 1.1.x, and 1.2.x are just published as "scala_2.12/sbt_1.0", since the 1.x versions of sbt are supposed to be binary compatible. Except they are not, in this case. So, the PR will fix the dbuild plugin for sbt 1.2, but it will break it for sbt 1.1.
I don't see an obvious way to write code that will work on both at the same time; the `reapply` calls are just different. I am thinking to use reflection; not very pretty but it might work. Or, a compatibility `reapply` might be added in sbt 1.2.1. Suggestions are welcome.

**Comment by dwijnand** [comment]
The 1.x versions of sbt _are_ binary compatible. dbuild is depending on internal sbt APIs that can break compatibility, and break they did.

I'd say expedite a fix based on reflection to unblock dbuild users.

**Comment by cunei** [comment]
Considering the sort of intertwining that dbuild has with sbt's internals, it's surprising it doesn't break more often. Working on it.

**Comment by dwijnand** [comment]
Indeed, it's a miracle it's survived this long.

**Comment by cunei** [comment]
The reflective calls seem to work ok (with some caveats). However, it seems some other changes are tripping dbuild with 1.2.0, it will need further work.
